[package]
name = "rust_2018_10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.49.2"
regex = "1.10.3"
relative-path = "1.9.2"
